---
- name: install direnv - apt install
  become: true
  apt:
    name: direnv
    update_cache: yes

- name: install direnv - hook direnv your shell
  lineinfile:
    path: "/home/{{ username }}/.zshrc"
    line: "eval "$(direnv hook zsh)""

- debug:
    msg: "Restart your shell for direnv to be activated."