---
- name: install docker - setup environment
  become: true
  apt: name={{item}} state=installed
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'software-properties-common'

- name: install docker - add docker gpg key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: install docker - add stable repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }}  stable"
    state: present

- name: install docker - install docker-ce package
  become: true
  apt:
    name: docker-ce
    state: present