---
- name: install git-cliff - set version
  set_fact:
    git_cliff_version: "0.3.0"

- name: install git-cliff - set facts for installation
  set_fact:
    git_cliff_install_dir:    "/home/{{ username }}/git-cliff-install"
    git_cliff_download_url:   "https://github.com/orhun/git-cliff/releases/download/v{{ git_cliff_version }}/git-cliff-{{ git_cliff_version }}-x86_64-unknown-linux-gnu.tar.gz"

- name: install git-cliff - create ~/git-cliff-install
  file:
    path: "{{ git_cliff_install_dir }}"
    state: directory
    force: yes

- name: install git-cliff - download git-cliff zip file
  get_url:
    url: "{{ git_cliff_download_url }}"
    dest: "{{ git_cliff_install_dir }}/git-cliff.tar.gz"
    mode: 0660

- name: install git-cliff - make local bin dir
  file:
    path: "/home/{{ username }}/.local/bin"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    force: yes

- name: install git-cliff - unzip git-cliff archive
  unarchive:
    src: "{{ git_cliff_install_dir }}/git-cliff.tar.gz"
    dest: "/home/{{ username }}/.local/bin/"

- name: install git-cliff - symlink git-cliff to /bin
  become: true
  file:
    src: "/home/{{ username }}/.local/bin/git-cliff-{{ git_cliff_version }}/git-cliff"
    dest: "/bin/git-cliff"
    state: link

- name: cleanup git-cliff install dirs
  file:
    path: "{{ git_cliff_install_dir }}"
    state: absent
