---
- name: install keepassxc - add repository
  become: true
  apt_repository:
    repo: "ppa:phoerious/keepassxc"
    state: present

- name: install keepassxc - install
  become: true
  apt:
    name: keepassxc
    update_cache: yes